# Generated by Django 3.0.5 on 2020-04-17 09:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_auto_20200411_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeprovider',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='attributeprovider',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='attributeprovider',
            name='name',
            field=models.CharField(help_text='', max_length=256),
        ),
        migrations.AlterField(
            model_name='attributeprovider',
            name='url',
            field=models.CharField(help_text='', max_length=512),
        ),
        migrations.AlterField(
            model_name='identity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='identityaddress',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='identityaddress',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='identitydelivery',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='identitydelivery',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='identityradiusaccount',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='identityradiusaccount',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='https://freeradmanager.it/identity/radius_renew/$token', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='identityradiusaccount',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identitythirdpartiesattribute',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='identitythirdpartiesattribute',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
