# Generated by Django 3.0.5 on 2020-04-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_auto_20200417_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeprovider',
            name='name',
            field=models.CharField(help_text='', max_length=256),
        ),
        migrations.AlterField(
            model_name='attributeprovider',
            name='url',
            field=models.CharField(help_text='', max_length=512),
        ),
    ]
